### ISSUE TITLE
Exceptions when creating index

### ISSUE THREAD

**Issue by xyliaaaaa** [amagge/geonames-service#1]
Hi! I came across some exceptions when building the index, as the picture shows. Then I could still run the service but it couldn't return the correct answer.

![image](https://user-images.githubusercontent.com/38355374/74458205-508a0300-4ec4-11ea-8acd-091e02d7885c.png)

**Comment by amagge** [comment]
Perhaps there is some problem in the downloaded admin files. I should do a safety check and handle exception either way. Will fix this soon. Thanks for reporting.

**Comment by amagge** [comment]
should be fixed by latest commit.

**Comment by xyliaaaaa** [comment]
Thank you! I finally ran the program successfully with IDE and another PC. The previous problem may be caused by my Maven or something.
